# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageRepositoryConsumer: 'techchallengefase3consumer'
  imageRepositoryProducer: 'techchallengefase3producer'
  containerRegistry: 'andrehs.azurecr.io'
  dockerfilePathConsumer: '$(Build.SourcesDirectory)/FIAP.Consumer/Dockerfile'
  dockerfilePathProducer: '$(Build.SourcesDirectory)/FIAP.Producer/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: FileTransform@1
      displayName: Replace variables - Consumer
      inputs:
        folderPath: '$(Build.SourcesDirectory)/FIAP.Consumer/FIAP.Consumer.csproj'
        fileType: 'json'
        targetFiles: 'appsettings.json'
    - task: Docker@2
      displayName: Build and push an image to container registry - Consumer
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryConsumer)
        dockerfile: $(dockerfilePathConsumer)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: FileTransform@1
      displayName: Replace variables - Producer
      inputs:
        folderPath: '$(Build.SourcesDirectory)/FIAP.Producer/FIAP.Producer.csproj'
        fileType: 'json'
        targetFiles: 'appsettings.json'
    - task: Docker@2
      displayName: Build and push an image to container registry - Producer
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryProducer)
        dockerfile: $(dockerfilePathProducer)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
